config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "game#index"
  get 'start', to: 'game#start'
  post 'start', to: 'game#start'
  get 'restart', to: 'game#restart'

  get 'stats', to: "game#stats"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/score.rb
class Score < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/game_controller.rb
class GameController < ApplicationController
    self.per_form_csrf_tokens = true
    before_action :save_details, only: %i[start]

    # Root Page of the Application
    def index
        session[:scores] = ["","","","","","","","",""]
    end

    # Contains Game Layout and Player Details 
    def start
        puts session[:player1]
        logger.info("New Game Started")
    end

    # Returns Game Details in Json Format
    def stats
        puts params
        session[:status] = "running"
        idx =  params[:box]
        if session[:scores][idx.to_i] == ""
            session[:scores][idx.to_i] = params[:choice]
        end
        session[:current_player] = params[:id].to_i
        print session[:scores]
        puts()
        logger.info("Player #{params[:id]} Has played move #{params[:box]}")
        respond_to do |format|
            if check_result(session[:scores])
                logger.info("player #{params[:id]} won the game")
                puts "player #{params[:id]} won the game"
                msg = {:id => params[:id], :success => "ok", :scores => session[:scores], :result => "win", :turns => count_turns }
                format.json { render json: msg, status: :ok }
            else
                msg = {:id => params[:id], :success => "ok", :scores => session[:scores], :result => "", :turns => count_turns}
                output = { status: 200, message: 'OK' }
                format.json { render json: msg, status: :ok }
            end
        end    
    end

    # Resets the Sessions and redirects to the home page after successfull execution
    def restart
        session[:status] = ""
        session[:current_player] = ""
        session[:scores] = ["","","","","","","","",""]
        session[:player1] = nil
        session[:player2] = nil
        session[:choice1] = nil
        session[:choice2] = nil
        redirect_to :action => "index"
    end

    private

    # Creates sessions for players and their choices 
    def save_details
        begin 
            if session[:player1].nil? && session[:player2].nil? && session[:choice1].nil? && session[:choice2].nil?
                session[:player1] = params[:player1].chomp
                session[:player2] = params[:player2].chomp
                session[:choice1] = params[:choice1].chomp
                session[:choice2] = params[:choice2].chomp
            end
        rescue Exception => exc 
            redirect_to :action => "index"
        end
    end

=begin
score = [
    [0,1,2]
    [3,4,5]
    [6,7,8]
]
 conditios to win =[
     [0,1,2]
     [3,4,5]
     [6,7,8]
     [0,4,8]
     [2,4,6]
     [0,3,6]
     [1,4,7]
     [2,5,8]
 ]        
=end

    # Checks for the Winning condition Mentioned Above
    def check_result(scores)
        if (check_condition(scores, 0, 1, 2) || check_condition(scores, 3, 4, 5) || check_condition(scores, 6, 7, 8) ||
            check_condition(scores, 0, 3, 6) || check_condition(scores, 1, 4, 7) || check_condition(scores, 2, 5, 8) ||
            check_condition(scores, 0, 4, 8) || check_condition(scores, 2, 4, 6))
            return true
        end
        return false
    end

    # Function for code resueability and for checking winning conditions
    def check_condition(scores, id1, id2, id3)
        if(scores[id1] != "" && scores[id2] != "" && scores[id3] != "" && scores[id1] == scores[id2] && scores[id2] == scores[id3])
            return true
        end
        return false
    end

    # Counts how many boxes have been marked
    def count_turns
        session[:turns] = 0
        for score in session[:scores].each
            if score != ""
                session[:turns] += 1
            end
        end
        return session[:turns]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/game/index.html.erb
<div class="container">
        <h1>Tic Tac Toe</h1>
        <form method="POST" action="<%= start_path %>">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">


        <!-- Player One Details -->
        <div class="row w-100" >
        <div class="col-6">
        <input type="text" class="form-control mb-2 mt-2" placeholder="Player 1" name="player1" required/>
        </div>
        <div class="col-6">
        <select class="form-select mt-2" aria-label="Default select example" name="choice1" id="choice1" required="required">
            <option selected value="X">Select X or O</option>
            <option value="X">X</option>
            <option value="O">O</option>
        </select>
        </div>
        </div>
        <!-- Player One Details Ends Here -->


        <!-- Player Two Details -->
        <div class="row w-100">
        <div class="col-6">
        <input type="text" class="form-control" placeholder="Player 2" name="player2" required />
        </div>
        <div class="col-6">
        <select class="form-select " aria-label="Default select example" name="choice2" id="choice2" required>
            <option selected value="O">Select X or O</option>
            <option value="X">X</option>
            <option value="O">O</option>
        </select>
        </div>
        </div>
        <!-- Player Two Details Ends Here -->


        <input type="submit" class="center btn btn-warning mt-2" id="start-btn" value="Start Game">
        </form>
</div>
<script type="text/javascript">
$("#choice1").change(function(){
    var option = $(this).find('option:selected');
    if(option.val() =="X"){
        $("#choice2").val("O");
    }
    else{
        $("#choice2").val("X");
    }  
});

$("#choice2").change(function(){
    var option = $(this).find('option:selected');
    if(option.val() =="X"){
        $("#choice1").val("O");
    }
    else{
        $("#choice1").val("X");
    }  
});
</script>

app/views/game/result.html.erb
<div id ="scores">
</div>

app/views/game/start.html.erb
<div class="container">
        <h1 id="heading">Play</h1>

        <!-- Player 1 Details -->
        <div class="row">
        <div class="col-5">
        <p style="color:white;"><%= session[:player1] %></p>
        </div>
        <div class="col-2" style="color:white;">:</div>
        <div class="col-5">
        <p style="color:white;text-align:right;"><%= session[:choice1] %></p>
        </div>
        </div>
        <!-- Player 1 Details Ends -->

        <!-- Player 2 Details -->
        <div class="row">
        <div class="col-5">
        <p style="color:white;"><%= session[:player2] %></p>
        </div>
        <div class="col-2" style="color:white;">:</div>
        <div class="col-5">
        <p style="color:white;text-align:right;"><%= session[:choice2] %></p>
        </div>
        </div>
        <!-- Player 2 Details Ends -->

        <!-- Playing Details -->
        <p style="color:yellow;" id="curr_player">sd</p>
        <!-- Playing Details Ends-->

        <!-- Game Board Section -->
        <form>
            <div id="board">
                <div class="box" id="0" onclick="fillbox(event,0);"></div>
                <div class="box" id="1" onclick="fillbox(event,1);"></div>
                <div class="box" id="2" onclick="fillbox(event,2);"></div>
                <div class="box" id="3" onclick="fillbox(event,3);"></div>
                <div class="box" id="4" onclick="fillbox(event,4);"></div>
                <div class="box" id="5" onclick="fillbox(event,5);"></div>
                <div class="box" id="6" onclick="fillbox(event,6);"></div>
                <div class="box" id="7" onclick="fillbox(event,7);"></div>
                <div class="box" id="8" onclick="fillbox(event,8);"></div>
            </div>
        </form>
        <!-- Game Board Section Ends Here -->

        <a id="restart" class="mt-2" href="<%= restart_path %>">End Match</a>
            
        
        <!-- Show Result Modal -->
        <div class="container" id="modal" data-keyboard="false" data-backdrop="static" style="border-radius:20px;">
            <h2 id="header_modal" >Congratulations</h2>
            <p style="color:white;" id="displayresult"></p> 
            <a class="btn btn-warning" href="<%= restart_path %>">Restart Game</a>           
            </div>  
        </div>
        <!-- Show Result Modal Ends --> 

</div>

<script>
curr_player_id = 1;
curr_player_choice = "<%= session[:choice1]%>";

$( document ).ready(function() {
    var game_status = 0;
    <% session[:scores].each do |score| %>
        <% if score != "" %>
            game_status = 1;
        <% end %>
    <% end %>

    if(game_status == 1){
        var ans = confirm("Do you wanna continue your previous game?")
        if (ans == true){
            <% session[:scores].each_with_index do |score, idx| %>
            $("#<%= idx %>").html("<%= score %>");
            <% end %>
            curr_player_id = parseInt("<%= session[:current_player]%>");
        }
        else{
            window.location.href = "<%= restart_path %>";
        }
    }
});


function updateplayer(player){
    $("#curr_player").html(`Player ${player} is playing`);
}
updateplayer(curr_player_id);

function display_result(player){
    if(player == 1){
        $("#displayresult").html("<%= session[:player1] %> Has Won!");
        $("#curr_player").html(`Game Ended`);
    }
    else{
        $("#displayresult").html("<%= session[:player2] %> Has Won!");
        $("#curr_player").html(`Game Ended`);
    }
    $("#modal").css("visibility", "visible");
}


function display_data(scores){
    for(var i = 0; i < scores.length; i++){
        $(`#${i}`).html(scores[i]);
    }
}


function fillbox(e,id){
    e.preventDefault();
    $.ajax({
    type: "GET",
    url: "/stats.json",
    data: {"id":curr_player_id,"box": id, "choice" : curr_player_choice},
    cache: false,
    success: function(result){
                display_data(result.scores);
                console.log(result);
                if(result.turns == 9){
                    $("#displayresult").html(`Game Has Tied!`);
                    $("#header_modal").html("Oops!");
                    $("#modal").css("visibility", "visible");
                    $("#curr_player").html(`Game Ended`);
                    return;
                }
                if(result.result == "win"){
                    display_result( curr_player_id );
                    return;
                }
                curr_player_id = (curr_player_id == 1 )? 2 :1
                curr_player_choice = (curr_player_choice == "X" )? "O" : "X"
                updateplayer(curr_player_id);
                return;
            }
    
    });
}


</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tic Tac Toe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>  </head>
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
  <body>
    <%= yield %>
  </body>
</html>